### ISSUE TITLE
[Bug] Single entity material configuration is propagated

### ISSUE THREAD

**Issue by GuilleX7** [GuilleX7/ExplodeAny#35]
**Describe the bug**
When a group of entities is configured and then a single entity, the single entity seems to override all entity-material configurations in groups which the single entity belongs to.

**To Reproduce**
Use the following config:

```yaml
VanillaEntity:
  ExplosiveEntities:
    Properties:
      ExplosionDamageBlocksUnderwater: false
    Materials:
      ExplosiveMaterials:
        Damage: 10.0
        DropChance: 50.0
        UnderwaterDamageFactor: 0.0
  CHARGED_CREEPER:
    Materials:
      ExplosiveMaterials:
        Damage: 40.0
        DropChance: 100.0
        UnderwaterDamageFactor: 0.5 
```

**Expected behavior**
`/eany config show VanillaEntity CREEPER OBSIDIAN` should display Damage: 10.0
`/eany config show VanillaEntity CHARGED_CREEPER OBSIDIAN` should display Damage: 40.0

**Current behavior**
`/eany config show VanillaEntity CREEPER OBSIDIAN` displays Damage: 40.0
`/eany config show VanillaEntity CHARGED_CREEPER OBSIDIAN` displays Damage: 40.0

**Minecraft server details:**
 - Any
